spring.application.name=homologacao
# Configurações do Banco de Dados (Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/homologacao_db
spring.datasource.username=postgres
spring.datasource.password=senha_forte
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialeto para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect